services:
#  mysql:
#    image: 'mysql:5.7'
#    ports:
#      - '3307'
#    labels:
#      org.springframework.boot.service-connection: mysql
#  minio:
#    image: 'my/minio'
#    ports:
#      - '9000'
#      - '9090'
#    labels:
#      org.springframework.boot.service-connection: minio
#  redis:
#    image: 'my/redis'
#    ports:
#      - '6379'
#    labels:
#      org.springframework.boot.service-connection: redis
#  rabbitmq:
#    image: 'rabbitmq'
#    ports:
#      - '5672'
#    labels:
#      org.springframework.boot.service-connection: rabbitmq
