server:
  port: 80
ip: ~~~
spring:
  application:
    name: Todo-Application
  datasource:
    url: jdbc:mysql://${ip}:3307/todo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ~~~~
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: ${ip}
      port: 6379
      database: 0
      password: ~~~~
      timeout: 30000s
      lettuce:
        pool:
          max-active: 8
          max-wait: 60000ms
          max-idle: 8
          min-idle: 0

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: yuxin_798@163.com
    password: ~~~
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
    protocol: smtp
    port: 465
  rabbitmq:
    addresses: ${ip}
    port: 5672
    username: guest
    password: ~~~
    listener:
      direct:
        retry:
          enabled: true
          initial-interval: "2s"
    stream:
      name: "my_stream"
  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  level:
    com.todo: debug
    web: trace
  pattern:
    dateformat: yyyy/MM/dd HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: deleted

todo:
  minio:
    endpoint: http://${ip}:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: todo-bucket
    allowed-content-type:
      "[image/png]": png
      "[image/jpg]": jpg
      "[image/jpeg]": jpeg
      "[image/gif]": gif
      "[video/mp4]": mp4
      "[image/*]": jpg
  task:
    db:
      cleaner:
        # 删除的天数
        days-of-deleted: 7

        # 每周三凌晨三点执行
        cron_schedule: "0 0 3 ? * 4"
#        cron_schedule: "* * * * * ?"

        # 要清理的表名
        table-names:
          - "todo.chat_message"
          - "todo.room"
          - "todo.task"
          - "todo.tomato_clock"
          - "todo.user"
          - "todo.user_room"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'Todo'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.todo

#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: false
  setting:
    language: zh_cn
    enable-version: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
