server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://8.130.17.7:3307/todo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 8.130.17.7
      port: 6379
      database: 0
      password: 147258369
      timeout: 30000s
      lettuce:
        pool:
          max-active: 8
          max-wait: 60000ms
          max-idle: 8
          min-idle: 0

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: yuxin_798@163.com
    password: EOTVAPNXIGLIPDOR
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
    protocol: smtp
    port: 465

logging:
  level:
    com.todo: debug
    web: trace
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: deleted

trust:
  minio:
    endpoint: http://8.130.17.7:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: todo-bucket
    allowed-content-type:
      "[image/png]": png
      "[image/jpg]": jpg
      "[image/jpeg]": jpeg
      "[image/gif]": gif
      "[video/mp4]": mp4

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'Todo'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.todo

#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: false
  setting:
    language: zh_cn
    enable-version: true
